apiVersion: azure.crossplane.io/v1alpha3
kind: Provider
metadata:
  name: azure-provider
  namespace: crossplane-system
spec:
  credentialsSecretRef:
    namespace: crossplane-system
    name: azure-secret
